# Generated by Django 3.2.9 on 2021-11-24 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20211123_1444'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='desrciption',
            new_name='description',
        ),
    ]
